name: CI/CD Pipeline for Cloud Storage Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      GOOGLE_DRIVE_API_KEY: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
      GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
      ONEDRIVE_API_KEY: ${{ secrets.ONEDRIVE_API_KEY }}
      DROPBOX_API_KEY: ${{ secrets.DROPBOX_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          sudo apt-get install rclone
          rclone version

      - name: Configure rclone remotes
        run: |
          echo "[gdrive]" > ~/.config/rclone/rclone.conf
          echo "type = drive" >> ~/.config/rclone/rclone.conf
          echo "client_id = ${GOOGLE_DRIVE_API_KEY}" >> ~/.config/rclone/rclone.conf
          echo "client_secret = ${GOOGLE_DRIVE_FOLDER_ID}" >> ~/.config/rclone/rclone.conf
          echo "token = ${GOOGLE_DRIVE_API_KEY}" >> ~/.config/rclone/rclone.conf
          echo "[onedrive]" >> ~/.config/rclone/rclone.conf
          echo "type = onedrive" >> ~/.config/rclone/rclone.conf
          echo "token = ${ONEDRIVE_API_KEY}" >> ~/.config/rclone/rclone.conf
          echo "[dropbox]" >> ~/.config/rclone/rclone.conf
          echo "type = dropbox" >> ~/.config/rclone/rclone.conf
          echo "token = ${DROPBOX_API_KEY}" >> ~/.config/rclone/rclone.conf

      - name: Upload to Google Drive
        run: |
          rclone copy /path/to/test/results gdrive:/Group10_project

      - name: Upload to OneDrive
        run: |
          rclone copy /path/to/test/results onedrive:/Group10_project

      - name: Upload to Dropbox
        run: |
          rclone copy /path/to/test/results dropbox:/Group10_project
